#!{{ parts.buildout.directory }}/bin/python
from couchdb import Server
from couchdb.design import ViewDefinition
from openprocurement.api.models import get_now
from datetime import timedelta
aserver = Server('http://{{ parts['couchdb.ini'].admin_username+':'+parts['couchdb.ini'].admin_username+'@' if parts['couchdb.ini'].admin_username else '' }}{{parts['couchdb.ini'].host}}:{{parts['couchdb.ini'].port}}/')
adb = aserver['{{ parts['openprocurement.api.ini'].couchdb_db }}']
server = Server('http://{{ parts['couchdb.ini'].username + ':' + parts['couchdb.ini'].password + '@' if parts['couchdb.ini'].username else '' }}{{ parts['couchdb.ini'].host}}:{{ parts['couchdb.ini'].port}}/')
db = server['{{ parts['openprocurement.api.ini'].couchdb_db }}']
shredder_view = ViewDefinition('shredder', 'tenders', "function(doc){if(doc.doc_type=='Tender' && doc.status=='draft'){emit(doc.dateModified, doc._rev)}")
ViewDefinition.sync_many(adb, [shredder_view])
date = (get_now() - timedelta(7)).isoformat()
tenders = []
for i in shredder_view(db, endkey=date):
    tenders.append({'_id': i.id, '_rev': i.value, '_deleted': True})
print db.update(tenders)
